### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by yatesco** [adpi2/scala3-full-stack-example#4]
Hi there - I did a clean download just now and when running `webserver/run` on the `main` branch I get the following error:

```scala
sbt:scala3-full-stack-example> webserver / run
[info] compiling 3 Scala sources to /home/coliny/Dev/scala3-full-stack-example/webpage/target/scala-3.0.2/classes ...
[error] -- [E006] Not Found Error: /home/coliny/Dev/scala3-full-stack-example/webpage/src/main/scala/example/HttpClient.scala:31:18
[error] 31 |    val request = Request(
[error]    |                  ^^^^^^^
[error]    |                  Not found: Request
[error] -- [E006] Not Found Error: /home/coliny/Dev/scala3-full-stack-example/webpage/src/main/scala/example/HttpClient.scala:34:8
[error] 34 |        method = HttpMethod.POST
[error]    |        ^^^^^^
[error]    |        Not found: method
[error] -- [E006] Not Found Error: /home/coliny/Dev/scala3-full-stack-example/webpage/src/main/scala/example/HttpClient.scala:35:8
[error] 35 |        headers = js.Dictionary("Content-Type" -> "application/json")
[error]    |        ^^^^^^^
[error]    |        Not found: headers
[error] -- [E006] Not Found Error: /home/coliny/Dev/scala3-full-stack-example/webpage/src/main/scala/example/HttpClient.scala:36:8
[error] 36 |        body = printer.print(CreateNote(title, content).asJson)
[error]    |        ^^^^
[error]    |        Not found: body
[error] -- [E100] Syntax Error: /home/coliny/Dev/scala3-full-stack-example/webpage/src/main/scala/example/HttpClient.scala:45:27
[error] 45 |      if resp.ok then resp.json.toFuture
[error]    |                      ^^^^^^^^^
[error]    |               method json in trait Body must be called with () argument
[error] 5 errors found
[error] 5 errors found
[error] (webpage / Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Dec 12, 2021, 2:07:49 AM
sbt:scala3-full-stack-example>
```

Any suggestions - thanks!

**Comment by yatesco** [comment]
Note that the previous commit (4d6fc15fd9ce405ae1dfcc19bbcc145753f20e16) works.

**Comment by adpi2** [comment]
Thanks @yatesco! I forgot to change the calls to the scalajs-dom API after bumping to 2.0.0. I just fixed that.
